<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/02/04 22:50:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=orangehrm',
  'username' => 'orangehrm',
  'password' => 'orangehrm',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
